version: "3"
services:
  postgres:
    env_file:
      - .env
    image: postgres:11.3-alpine

  processing:
    build:
      context: processing
      args:
        - LOCAL_USER_ID
    depends_on:
      - postgres
    env_file:
      - .env
    volumes:
      - ${DATA_FOLDER}:/mnt/data
      - ${PROCESSING_FOLDER}:/mnt/code
